services:
  op-connect-api:
    image: 1password/connect-api:latest
    container_name: 1pwd-connect-api
    ports:
      - "8080:8080"
    volumes:
      - "/home/jlm/1pwd/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
  op-connect-sync:
    image: 1password/connect-sync:latest
    container_name: 1pwd-connect-sync
    ports:
      - "8081:8080"
    volumes:
      - "/home/jlm/1pwd/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
  huqs:
    image: jeanlaurent/huqs:latest
    container_name: huqs
    ports:
      - "8088:8080"
    environment:
      - OP_CONNECT_HOST=http://op-connect-api:8080
      - OP_CONNECT_TOKEN=${OP_CONNECT_TOKEN}
    depends_on:
      - op-connect-api
      - op-connect-sync