name: Deploy huqs image to hub

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
          username: jeanlaurent
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Set up Docker Build Cloud
      uses: docker/setup-buildx-action@v3
      with:
        version: "lab:latest"
        driver: cloud
        endpoint: "docker/platform-experience"
        install: true

    - name: Creating Docker Image Labels
      id: meta
      uses: docker/metadata-action@v4
      with:
         images: |
            jeanlaurent/huqs
         tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'main') }}
            
    - name: Building and pushing image
      uses: docker/build-push-action@v5
      with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          sbom: true
          provenance: mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
